# Generated by Django 5.2.4 on 2025-07-11 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="churned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="deal_closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="estimated_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="funnel_stage",
            field=models.CharField(
                choices=[
                    ("form_submitted", "Form Submitted"),
                    ("meeting_booked", "Meeting Booked"),
                    ("meeting_held", "Meeting Held"),
                    ("pilot_signed", "Pilot Signed"),
                    ("deal_closed", "Deal Closed"),
                    ("churned", "Churned"),
                ],
                default="form_submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="funnel_stage_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_score",
            field=models.IntegerField(default=0, help_text="Lead quality score 0-100"),
        ),
        migrations.AddField(
            model_name="lead",
            name="meeting_booked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="meeting_held_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="pilot_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FunnelStageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("form_submitted", "Form Submitted"),
                            ("meeting_booked", "Meeting Booked"),
                            ("meeting_held", "Meeting Held"),
                            ("pilot_signed", "Pilot Signed"),
                            ("deal_closed", "Deal Closed"),
                            ("churned", "Churned"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "to_stage",
                    models.CharField(
                        choices=[
                            ("form_submitted", "Form Submitted"),
                            ("meeting_booked", "Meeting Booked"),
                            ("meeting_held", "Meeting Held"),
                            ("pilot_signed", "Pilot Signed"),
                            ("deal_closed", "Deal Closed"),
                            ("churned", "Churned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_history",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
