# Generated by Django 5.2.4 on 2025-07-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_lead_churned_at_lead_deal_closed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="cvr_last_updated",
            field=models.DateTimeField(
                blank=True, help_text="When CVR data was last fetched", null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="cvr_number",
            field=models.CharField(
                blank=True, help_text="Danish CVR number", max_length=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="icp_score",
            field=models.IntegerField(
                default=4, help_text="ICP matching score (4-12 points)"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="icp_score_breakdown",
            field=models.JSONField(
                blank=True, default=dict, help_text="Detailed ICP scoring breakdown"
            ),
        ),
    ]
