# Generated by Django 5.2.4 on 2025-07-14 20:23

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0001_initial"),
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('dayGridMonth', 'Month View'), ('timeGridWeek', 'Week View'), ('timeGridDay', 'Day View'), ('listWeek', 'List View')], default='dayGridMonth', max_length=20)),
                ('show_weekends', models.BooleanField(default=True)),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('default_event_types', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_account_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar View Preference',
                'verbose_name_plural': 'Calendar View Preferences',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('appointment', 'Appointment'), ('reminder', 'Reminder'), ('holiday', 'Holiday'), ('personal', 'Personal Event'), ('company', 'Company Event'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_url', models.URLField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                # Note: GenericForeignKey fields ('related_object') are not included in migrations as they are not actual database fields
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'View and Edit'), ('admin', 'Full Access')], default='view', max_length=10)),
                ('include_tasks', models.BooleanField(default=True)),
                ('include_calls', models.BooleanField(default=True)),
                ('include_meetings', models.BooleanField(default=True)),
                ('include_custom_events', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendars', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessible_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Share',
                'verbose_name_plural': 'Calendar Shares',
            },
        ),
        migrations.CreateModel(
            name='CalendarNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('browser', 'Browser Notification'), ('sms', 'SMS')], max_length=20)),
                ('minutes_before', models.PositiveIntegerField(default=15)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                # Note: GenericForeignKey fields ('event') are not included in migrations as they are not actual database fields
            ],
            options={
                'verbose_name': 'Calendar Notification',
                'verbose_name_plural': 'Calendar Notifications',
            },
        ),
        migrations.AddConstraint(
            model_name='calendarshare',
            constraint=models.UniqueConstraint(fields=('owner', 'shared_with'), name='calendar_app_calendarshare_owner_shared_with_uniq'),
        ),
        migrations.AddConstraint(
            model_name='calendarnotification',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id', 'notification_type'), name='calendar_app_calendarnotification_user_content_type_object_id_notification_type_uniq'),
        ),
    ]
