# Generated by Django 5.2.4 on 2025-07-14 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_app", "0002_auto_20250714_2223"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="calendarnotification",
            name="calendar_app_calendarnotification_user_content_type_object_id_notification_type_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="calendarshare",
            name="calendar_app_calendarshare_owner_shared_with_uniq",
        ),
        migrations.AlterUniqueTogether(
            name="calendarnotification",
            unique_together={
                ("user", "content_type", "object_id", "notification_type")
            },
        ),
        migrations.AlterUniqueTogether(
            name="calendarshare",
            unique_together={("owner", "shared_with")},
        ),
    ]
