# Generated by Django 5.2.4 on 2025-07-10 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("contacts", "0001_initial"),
        ("leads", "0001_initial"),
        ("opportunities", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ["-start_datetime"]},
        ),
        migrations.RenameField(
            model_name="meeting",
            old_name="start_date",
            new_name="start_datetime",
        ),
        migrations.RenameField(
            model_name="meeting",
            old_name="name",
            new_name="subject",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="description",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="object_id",
        ),
        migrations.AddField(
            model_name="meeting",
            name="agenda",
            field=models.TextField(blank=True, help_text="Meeting agenda"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="attendees_notes",
            field=models.TextField(blank=True, help_text="List of attendees"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Planned duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="end_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_notes",
            field=models.TextField(
                blank=True, help_text="Notes taken during/after the meeting"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_type",
            field=models.CharField(
                choices=[
                    ("sales_meeting", "Sales Meeting"),
                    ("demo", "Product Demo"),
                    ("follow_up", "Follow-up Meeting"),
                    ("negotiation", "Negotiation"),
                    ("kickoff", "Project Kickoff"),
                    ("review", "Review Meeting"),
                    ("training", "Training"),
                    ("other", "Other"),
                ],
                default="sales_meeting",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="meeting_url",
            field=models.URLField(blank=True, help_text="Video conference URL"),
        ),
        migrations.AddField(
            model_name="meeting",
            name="outcome",
            field=models.TextField(
                blank=True, help_text="Meeting outcome and next steps"
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_meetings",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="related_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="related_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="related_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="related_opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=models.CharField(
                blank=True, help_text="Meeting location or 'Online'", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("postponed", "Postponed"),
                    ("no_show", "No Show"),
                ],
                default="planned",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "call_type",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="outbound",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_answer", "No Answer"),
                            ("busy", "Busy"),
                            ("left_message", "Left Message"),
                        ],
                        default="planned",
                        max_length=15,
                    ),
                ),
                (
                    "call_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("callback_requested", "Callback Requested"),
                            ("voicemail", "Voicemail"),
                            ("busy", "Busy"),
                            ("no_answer", "No Answer"),
                            ("wrong_number", "Wrong Number"),
                            ("meeting_scheduled", "Meeting Scheduled"),
                            ("sale_closed", "Sale Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                ("scheduled_datetime", models.DateTimeField()),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Call agenda or notes"),
                ),
                (
                    "call_notes",
                    models.TextField(
                        blank=True, help_text="Notes taken during/after the call"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="accounts.account",
                    ),
                ),
                (
                    "related_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="contacts.contact",
                    ),
                ),
                (
                    "related_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="leads.lead",
                    ),
                ),
                (
                    "related_opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_datetime"],
            },
        ),
    ]
