# Generated by Django 5.2.4 on 2025-07-10 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "sales_stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospecting"),
                            ("qualification", "Qualification"),
                            ("needs_analysis", "Needs Analysis"),
                            ("value_proposition", "Value Proposition"),
                            ("id_decision_makers", "Id. Decision Makers"),
                            ("perception_analysis", "Perception Analysis"),
                            ("proposal", "Proposal/Price Quote"),
                            ("negotiation", "Negotiation/Review"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        default="prospecting",
                        max_length=20,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        default=0, help_text="Probability of closing (0-100%)"
                    ),
                ),
                ("expected_close_date", models.DateField()),
                (
                    "opportunity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("existing_business", "Existing Business"),
                            ("new_business", "New Business"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("existing_customer", "Existing Customer"),
                            ("partner", "Partner"),
                            ("public_relations", "Public Relations"),
                            ("direct_mail", "Direct Mail"),
                            ("conference", "Conference"),
                            ("trade_show", "Trade Show"),
                            ("web_site", "Web Site"),
                            ("word_of_mouth", "Word of mouth"),
                            ("email", "Email"),
                            ("campaign", "Campaign"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("next_step", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="accounts.account",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Opportunities",
                "ordering": ["-expected_close_date"],
            },
        ),
    ]
