# Generated by Django 5.2.4 on 2025-07-10 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("complete", "Complete"),
                        ],
                        default="planning",
                        max_length=15,
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conference", "Conference"),
                            ("webinar", "Webinar"),
                            ("trade_show", "Trade Show"),
                            ("public_relations", "Public Relations"),
                            ("partners", "Partners"),
                            ("direct_mail", "Direct Mail"),
                            ("email", "Email"),
                            ("telemarketing", "Telemarketing"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "budgeted_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "expected_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "expected_response",
                    models.CharField(
                        blank=True, help_text="Expected response rate %", max_length=10
                    ),
                ),
                ("num_sent", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("objective", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CampaignTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("contact", "Contact"), ("lead", "Lead")],
                        max_length=10,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("activity_date", models.DateTimeField(blank=True, null=True)),
                ("response", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "target_type", "target_id")},
            },
        ),
    ]
